### ISSUE TITLE
13 INTERNAL: Failed to parse server response

### ISSUE THREAD

**Issue by kop** [temporalio/web#157]
Hello,

I'm trying to test my first Temporal workflow and having issues with viewing execution history in UI.
I'm using Temporal Server & UI v1.0.0, CockroachDB v20.1.5.

UI fails with the following error:

![Temporal 2020-10-09 22-38-53](https://user-images.githubusercontent.com/645148/95624954-59959900-0a80-11eb-8a28-a28044335c97.png)

```
temporal-web_1          | Response deserialization failed: Cannot read property 'payloads' of null
temporal-web_1          | OperationalError: 13 INTERNAL: Failed to parse server response
temporal-web_1          |     at Object.exports.createStatusError (/usr/app/node_modules/grpc/src/common.js:91:15)
temporal-web_1          |     at Object.onReceiveStatus (/usr/app/node_modules/grpc/src/client_interceptors.js:1209:28)
temporal-web_1          |     at InterceptingListener._callNext (/usr/app/node_modules/grpc/src/client_interceptors.js:568:42)
temporal-web_1          |     at InterceptingListener.onReceiveStatus (/usr/app/node_modules/grpc/src/client_interceptors.js:618:8)
temporal-web_1          |     at callback (/usr/app/node_modules/grpc/src/client_interceptors.js:847:24) {
temporal-web_1          |   cause: Error: 13 INTERNAL: Failed to parse server response
temporal-web_1          |       at Object.exports.createStatusError (/usr/app/node_modules/grpc/src/common.js:91:15)
temporal-web_1          |       at Object.onReceiveStatus (/usr/app/node_modules/grpc/src/client_interceptors.js:1209:28)
temporal-web_1          |       at InterceptingListener._callNext (/usr/app/node_modules/grpc/src/client_interceptors.js:568:42)
temporal-web_1          |       at InterceptingListener.onReceiveStatus (/usr/app/node_modules/grpc/src/client_interceptors.js:618:8)
temporal-web_1          |       at callback (/usr/app/node_modules/grpc/src/client_interceptors.js:847:24) {
temporal-web_1          |     code: 13,
temporal-web_1          |     metadata: undefined,
temporal-web_1          |     details: 'Failed to parse server response'
temporal-web_1          |   },
temporal-web_1          |   isOperational: true,
temporal-web_1          |   code: 13,
temporal-web_1          |   metadata: undefined,
temporal-web_1          |   details: 'Failed to parse server response'
temporal-web_1          | }
```

The workflow itself works (I can see it in both my server logs and tctl).

<details><summary>tctl wf showid</summary>
<p>

```
   1  WorkflowExecutionStarted              {WorkflowType:{Name:DatabaseDelete}, ParentInitiatedEventId:0, TaskQueue:{Name:default, Kind:Normal},
                                            Input:[{"accountId":"23a41ebb-6546-409f-ba36-71c4cccd67d5","databaseId":"947f1513-80e3-479f-a3c0-d28dcdd8d332"},
                                            /users/5840cabc-8a87-4399-908a-a362366cbced], WorkflowExecutionTimeout:87600h0m0s,
                                            WorkflowRunTimeout:87600h0m0s, WorkflowTaskTimeout:10s, Initiator:Unspecified, LastCompletionResult:[],
                                            OriginalExecutionRunId:92161aff-7f79-4134-9872-b573f68ee3f1, Identity:25147@kop-laptop.local@,
                                            FirstExecutionRunId:92161aff-7f79-4134-9872-b573f68ee3f1, Attempt:1, WorkflowExecutionExpirationTime:2030-10-07
                                            18:42:19.342 +0000 UTC, FirstWorkflowTaskBackoff:0s, Header:{Fields:map{}}}
   2  WorkflowTaskScheduled                 {TaskQueue:{Name:default,
                                            Kind:Normal},
                                            StartToCloseTimeout:10s,
                                            Attempt:1}
   3  WorkflowTaskStarted                   {ScheduledEventId:2,
                                            Identity:25147@kop-laptop.local@,
                                            RequestId:bde3ee52-bb7e-44f1-af9d-38ec40308f10}
   4  WorkflowTaskCompleted                 {ScheduledEventId:2, StartedEventId:3,
                                            Identity:25147@kop-laptop.local@,
                                            BinaryChecksum:f4b66680fc0902d60899418609256894}
   5  MarkerRecorded                        {MarkerName:LocalActivity,
                                            Details:map{data:<*common.Payloads
                                            Value>, result:<*common.Payloads
                                            Value>},
                                            WorkflowTaskCompletedEventId:4}
   6  MarkerRecorded                        {MarkerName:LocalActivity,
                                            Details:map{result:<*common.Payloads
                                            Value>, data:<*common.Payloads
                                            Value>},
                                            WorkflowTaskCompletedEventId:4}
   7  StartChildWorkflowExecutionInitiated  {Namespace:default,
                                            WorkflowId:core_v1_BindingDelete_23a41ebb-6546-409f-ba36-71c4cccd67d5_947f1513-80e3-479f-a3c0-d28dcdd8d332_45c7b174-9e7a-4526-b784-
                                            99cd35b17fef, WorkflowType:{Name:BindingDelete}, TaskQueue:{Name:default, Kind:Normal},
                                            Input:[{"accountId":"23a41ebb-6546-409f-ba36-71c4cccd67d5","databaseId":"947f1513-80e3-479f-a3c0-d28dcdd8d332","engineId":"45c
                                            7b174-9e7a-4526-b784-99cd35b17fef"}, /users/5840cabc-8a87-4399-908a-a362366cbced], WorkflowExecutionTimeout:87600h0m0s,
                                            WorkflowRunTimeout:87600h0m0s, WorkflowTaskTimeout:10s, ParentClosePolicy:Terminate, WorkflowTaskCompletedEventId:4,
                                            WorkflowIdReusePolicy:AllowDuplicate, Header:{Fields:map{}}}
   8  ChildWorkflowExecutionStarted         {Namespace:default, InitiatedEventId:7,
                                            WorkflowExecution:{WorkflowId:core_v1_BindingDelete_23a41ebb-6546-409f-ba36-71c4cccd67d5_947f1513-80e3-479f-a3c0-d28dcdd8d332_45c7b174-9e7
                                            a-4526-b784- 99cd35b17fef, RunId:e997a231-7c83-4b65-8ce0-01d90e9d4f1b}, WorkflowType:{Name:BindingDelete}, Header:{Fields:map{}}}
   9  WorkflowTaskScheduled                 {TaskQueue:{Name:kop-laptop.local:9b4c035c-2d48-4405-b88e-99967d3118be,
                                            Kind:Sticky}, StartToCloseTimeout:10s, Attempt:1}
  10  WorkflowTaskStarted                   {ScheduledEventId:9,
                                            Identity:25147@kop-laptop.local@,
                                            RequestId:cde99505-a8f0-446e-b43c-e8ace5a9ba81}
  11  WorkflowTaskCompleted                 {ScheduledEventId:9, StartedEventId:10,
                                            Identity:25147@kop-laptop.local@,
                                            BinaryChecksum:f4b66680fc0902d60899418609256894}
  12  ChildWorkflowExecutionCompleted       {Result:[], Namespace:default,
                                            WorkflowExecution:{WorkflowId:core_v1_BindingDelete_23a41ebb-6546-409f-ba36-71c4cccd67d5_947f1513-80e3-479f-a3c0-d28dcdd8d332_45c7b174-9e7
                                            a-4526-b784- 99cd35b17fef, RunId:e997a231-7c83-4b65-8ce0-01d90e9d4f1b}, WorkflowType:{Name:BindingDelete}, InitiatedEventId:7,
                                            StartedEventId:8}
  13  WorkflowTaskScheduled                 {TaskQueue:{Name:kop-laptop.local:9b4c035c-2d48-4405-b88e-99967d3118be,
                                            Kind:Sticky}, StartToCloseTimeout:10s, Attempt:1}
  14  WorkflowTaskStarted                   {ScheduledEventId:13,
                                            Identity:25147@kop-laptop.local@,
                                            RequestId:f2c811d5-ffbd-412d-aa7d-4dc8b7e0d694}
  15  WorkflowTaskCompleted                 {ScheduledEventId:13, StartedEventId:14,
                                            Identity:25147@kop-laptop.local@,
                                            BinaryChecksum:f4b66680fc0902d60899418609256894}
  16  MarkerRecorded                        {MarkerName:LocalActivity,
                                            Details:map{result:<*common.Payloads
                                            Value>, data:<*common.Payloads
                                            Value>},
                                            WorkflowTaskCompletedEventId:15}
  17  MarkerRecorded                        {MarkerName:LocalActivity,
                                            Details:map{result:<*common.Payloads
                                            Value>, data:<*common.Payloads
                                            Value>},
                                            WorkflowTaskCompletedEventId:15}
  18  WorkflowExecutionSignaled             {SignalName:database_delete_signal,
                                            Input:[9],
                                            Identity:25147@kop-laptop.local@}
  19  WorkflowTaskScheduled                 {TaskQueue:{Name:kop-laptop.local:9b4c035c-2d48-4405-b88e-99967d3118be,
                                            Kind:Sticky}, StartToCloseTimeout:10s, Attempt:1}
  20  WorkflowTaskStarted                   {ScheduledEventId:19,
                                            Identity:25147@kop-laptop.local@,
                                            RequestId:54463a4d-d3fc-412c-8e46-37b5ba38aff7}
  21  WorkflowTaskCompleted                 {ScheduledEventId:19, StartedEventId:20,
                                            Identity:25147@kop-laptop.local@,
                                            BinaryChecksum:f4b66680fc0902d60899418609256894}
  22  MarkerRecorded                        {MarkerName:LocalActivity,
                                            Details:map{data:<*common.Payloads
                                            Value>, result:<*common.Payloads
                                            Value>},
                                            WorkflowTaskCompletedEventId:21}
  23  MarkerRecorded                        {MarkerName:LocalActivity,
                                            Details:map{result:<*common.Payloads
                                            Value>, data:<*common.Payloads
                                            Value>},
                                            WorkflowTaskCompletedEventId:21}
  24  WorkflowExecutionCompleted            {Result:[],
                                            WorkflowTaskCompletedEventId:21}
```

</p>
</details>

<details><summary>tctl wf descid</summary>
<p>

```json
{
  "executionConfig": {
    "taskQueue": {
      "name": "default",
      "kind": "Normal"
    },
    "workflowExecutionTimeout": "315360000s",
    "workflowRunTimeout": "315360000s",
    "defaultWorkflowTaskTimeout": "10s"
  },
  "workflowExecutionInfo": {
    "execution": {
      "workflowId": "core_v1_DatabaseDelete_23a41ebb-6546-409f-ba36-71c4cccd67d5_947f1513-80e3-479f-a3c0-d28dcdd8d332",
      "runId": "92161aff-7f79-4134-9872-b573f68ee3f1"
    },
    "type": {
      "name": "DatabaseDelete"
    },
    "startTime": "2020-10-09T18:42:19.365006300Z",
    "closeTime": "2020-10-09T18:42:20.204858800Z",
    "status": "Completed",
    "historyLength": "24",
    "memo": {

    },
    "searchAttributes": {
      "indexedFields": {
        "BinaryChecksums": "[f4b66680fc0902d60899418609256894]"
      }
    },
    "autoResetPoints": {
      "points": [
        {
          "binaryChecksum": "f4b66680fc0902d60899418609256894",
          "runId": "92161aff-7f79-4134-9872-b573f68ee3f1",
          "firstWorkflowTaskCompletedId": "4",
          "createTime": "2020-10-09T18:42:19.496305100Z",
          "resettable": true
        }
      ]
    }
  }
}
```

</p>
</details>

In the community forum, I've seen a couple of mentions of problems when Protobuf messages are passed as workflow/activity parameters. Those issues have been fixed, but now there is that new Go Protobuf API (`google.golang.org/protobuf`), which I use. Is it possible that is is the source of the problem?

**Comment by feedmeapples** [comment]
@kop have you ran into the same issue ever since? if yes, especially on newer versions of temporal server & web pls lmk

**Comment by kop** [comment]
@feedmeapples I did not. But I changed the format of the Workflow/Actions inputs -  this solved the issue.

Previously I passed them as multiple args, for example:

```go
	_, err = svc.temporalServiceClient.ExecuteWorkflow(
		ctx,
		temporal.StartWorkflowOptions{},
		workflows.MyWorkflow,
		arg1, arg2, arg3,
	)
```

And now I'm using struct as an input.

```go
	_, err = svc.temporalServiceClient.ExecuteWorkflow(
		ctx,
		temporal.StartWorkflowOptions{},
		workflows.MyWorkflow,
		workflows.MyWorkflowInput {
                     Arg1: arg1,
                     Arg2: arg2,
                     Arg3: arg3,
                 }
	)
```
