### ISSUE TITLE
[Bug] Temporal Web doesn't support Node 12

### ISSUE THREAD

**Issue by sw-yx** [temporalio/web#201]
**Describe the bug**

run temporal web in node 12 and we get this

```bash
> temporal-web@1.3.0 dev /Users/wanshawn/Work/Temporal/web
> NODE_ENV=development node server.js

/Users/wanshawn/Work/Temporal/web/server/index.js:32
    process.env.TEMPORAL_SESSION_SECRET ?? 'ensure secret in production';
                                         ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/wanshawn/Work/Temporal/web/server.js:1:11)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! temporal-web@1.3.0 dev: `NODE_ENV=development node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the temporal-web@1.3.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wanshawn/.npm/_logs/2020-11-16T20_36_50_923Z-debug.log
```

**Expected behavior**
it should just work

**Comment by sw-yx** [comment]
we'll just have a hard dependency on node 14.
