### ISSUE TITLE
Oidc login fail without any log

### ISSUE THREAD

**Issue by runzexia** [temporalio/web#377]
I tried set up oidc config, and when login, the callback uri shows error(base on route to sign in). I also check the log of web, but shows nothing..
![image](https://user-images.githubusercontent.com/31230341/131333990-61338dc4-d102-426d-916b-9e400be9230a.png)

```
(base) ➜  ~ kubectl logs -n smec temporal-web-7768f85795-pw562                     (eureka-ci)
I0830 18:32:05.800492   85849 request.go:645] Throttling request took 1.188837967s, request: GET:https://35.222.17.144/apis/operator.knative.dev/v1alpha1?timeout=32s
[2021-08-30T10:08:46.628Z] establishing insecure connection...
temporal-web up and listening on port 8088
[2021-08-30T10:09:12.991Z] Error: Request unauthorized
    at buildGrpcMetadata (/usr/app/server/temporal-client/with-auth-metadata.js:43:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Proxy.<anonymous> (/usr/app/server/temporal-client/with-auth-metadata.js:20:24)
    at async TemporalClient.getVersionInfo (/usr/app/server/temporal-client/temporal-client.js:294:15)
    at async Proxy.<anonymous> (/usr/app/server/temporal-client/with-error-converter.js:30:18)
    at async /usr/app/server/routes.js:388:15
    at async initialize (/usr/app/server/auth/index.js:47:3)
    at async session (/usr/app/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/usr/app/node_modules/koa-bodyparser/index.js:95:5)
    at async /usr/app/server/index.js:43:9
[2021-08-30T10:09:17.717Z] Error: Request unauthorized
    at buildGrpcMetadata (/usr/app/server/temporal-client/with-auth-metadata.js:43:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Proxy.<anonymous> (/usr/app/server/temporal-client/with-auth-metadata.js:20:24)
    at async TemporalClient.getVersionInfo (/usr/app/server/temporal-client/temporal-client.js:294:15)
    at async Proxy.<anonymous> (/usr/app/server/temporal-client/with-error-converter.js:30:18)
    at async /usr/app/server/routes.js:388:15
    at async initialize (/usr/app/server/auth/index.js:47:3)
    at async session (/usr/app/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/usr/app/node_modules/koa-bodyparser/index.js:95:5)
    at async /usr/app/server/index.js:43:9
[2021-08-30T10:09:24.989Z] Error: Request unauthorized
    at buildGrpcMetadata (/usr/app/server/temporal-client/with-auth-metadata.js:43:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Proxy.<anonymous> (/usr/app/server/temporal-client/with-auth-metadata.js:20:24)
    at async TemporalClient.getVersionInfo (/usr/app/server/temporal-client/temporal-client.js:294:15)
    at async Proxy.<anonymous> (/usr/app/server/temporal-client/with-error-converter.js:30:18)
    at async /usr/app/server/routes.js:388:15
    at async initialize (/usr/app/server/auth/index.js:47:3)
    at async session (/usr/app/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/usr/app/node_modules/koa-bodyparser/index.js:95:5)
    at async /usr/app/server/index.js:43:9
[2021-08-30T10:09:58.244Z] Error: Request unauthorized
    at buildGrpcMetadata (/usr/app/server/temporal-client/with-auth-metadata.js:43:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Proxy.<anonymous> (/usr/app/server/temporal-client/with-auth-metadata.js:20:24)
    at async TemporalClient.getVersionInfo (/usr/app/server/temporal-client/temporal-client.js:294:15)
    at async Proxy.<anonymous> (/usr/app/server/temporal-client/with-error-converter.js:30:18)
    at async /usr/app/server/routes.js:388:15
    at async initialize (/usr/app/server/auth/index.js:47:3)
    at async session (/usr/app/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/usr/app/node_modules/koa-bodyparser/index.js:95:5)
    at async /usr/app/server/index.js:43:9
[2021-08-30T10:13:11.595Z] Error: Request unauthorized
    at buildGrpcMetadata (/usr/app/server/temporal-client/with-auth-metadata.js:43:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Proxy.<anonymous> (/usr/app/server/temporal-client/with-auth-metadata.js:20:24)
    at async TemporalClient.getVersionInfo (/usr/app/server/temporal-client/temporal-client.js:294:15)
    at async Proxy.<anonymous> (/usr/app/server/temporal-client/with-error-converter.js:30:18)
    at async /usr/app/server/routes.js:388:15
    at async initialize (/usr/app/server/auth/index.js:47:3)
    at async session (/usr/app/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/usr/app/node_modules/koa-bodyparser/index.js:95:5)
    at async /usr/app/server/index.js:43:9
[2021-08-30T10:13:33.597Z] Error: Request unauthorized
    at buildGrpcMetadata (/usr/app/server/temporal-client/with-auth-metadata.js:43:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Proxy.<anonymous> (/usr/app/server/temporal-client/with-auth-metadata.js:20:24)
    at async TemporalClient.getVersionInfo (/usr/app/server/temporal-client/temporal-client.js:294:15)
    at async Proxy.<anonymous> (/usr/app/server/temporal-client/with-error-converter.js:30:18)
    at async /usr/app/server/routes.js:388:15
    at async initialize (/usr/app/server/auth/index.js:47:3)
    at async session (/usr/app/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/usr/app/node_modules/koa-bodyparser/index.js:95:5)
    at async /usr/app/server/index.js:43:9
[2021-08-30T10:13:47.002Z] Error: Request unauthorized
    at buildGrpcMetadata (/usr/app/server/temporal-client/with-auth-metadata.js:43:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Proxy.<anonymous> (/usr/app/server/temporal-client/with-auth-metadata.js:20:24)
    at async TemporalClient.getVersionInfo (/usr/app/server/temporal-client/temporal-client.js:294:15)
    at async Proxy.<anonymous> (/usr/app/server/temporal-client/with-error-converter.js:30:18)
    at async /usr/app/server/routes.js:388:15
    at async initialize (/usr/app/server/auth/index.js:47:3)
    at async session (/usr/app/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/usr/app/node_modules/koa-bodyparser/index.js:95:5)
    at async /usr/app/server/index.js:43:9
[2021-08-30T10:14:39.654Z] Error: did not find expected authorization request details in session, req.session["oidc:ids.uat-eureka.uat.eurekacloud.io"] is undefined
    at /usr/app/node_modules/openid-client/lib/passport_strategy.js:128:13
    at OpenIDConnectStrategy.authenticate (/usr/app/node_modules/openid-client/lib/passport_strategy.js:176:5)
    at attempt (/usr/app/node_modules/passport/lib/middleware/authenticate.js:366:16)
    at authenticate (/usr/app/node_modules/passport/lib/middleware/authenticate.js:367:7)
    at /usr/app/node_modules/koa-passport/lib/framework/koa.js:194:7
    at new Promise (<anonymous>)
    at /usr/app/node_modules/koa-passport/lib/framework/koa.js:193:12
    at /usr/app/node_modules/koa-passport/lib/framework/koa.js:143:7
    at new Promise (<anonymous>)
    at passportAuthenticate (/usr/app/node_modules/koa-passport/lib/framework/koa.js:107:15)
    at Object.authenticate (/usr/app/server/auth/index.js:55:4)
    at /usr/app/server/routes-auth.js:11:15
    at dispatch (/usr/app/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/usr/app/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /usr/app/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/usr/app/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
[2021-08-30T10:14:53.890Z] Error: did not find expected authorization request details in session, req.session["oidc:ids.uat-eureka.uat.eurekacloud.io"] is undefined
    at /usr/app/node_modules/openid-client/lib/passport_strategy.js:128:13
    at OpenIDConnectStrategy.authenticate (/usr/app/node_modules/openid-client/lib/passport_strategy.js:176:5)
    at attempt (/usr/app/node_modules/passport/lib/middleware/authenticate.js:366:16)
    at authenticate (/usr/app/node_modules/passport/lib/middleware/authenticate.js:367:7)
    at /usr/app/node_modules/koa-passport/lib/framework/koa.js:194:7
    at new Promise (<anonymous>)
    at /usr/app/node_modules/koa-passport/lib/framework/koa.js:193:12
    at /usr/app/node_modules/koa-passport/lib/framework/koa.js:143:7
    at new Promise (<anonymous>)
    at passportAuthenticate (/usr/app/node_modules/koa-passport/lib/framework/koa.js:107:15)
    at Object.authenticate (/usr/app/server/auth/index.js:55:4)
    at /usr/app/server/routes-auth.js:11:15
    at dispatch (/usr/app/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/usr/app/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /usr/app/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/usr/app/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
[2021-08-30T10:23:34.099Z] Error: Request unauthorized
    at buildGrpcMetadata (/usr/app/server/temporal-client/with-auth-metadata.js:43:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Proxy.<anonymous> (/usr/app/server/temporal-client/with-auth-metadata.js:20:24)
    at async TemporalClient.listNamespaces (/usr/app/server/temporal-client/temporal-client.js:77:15)
    at async Proxy.<anonymous> (/usr/app/server/temporal-client/with-error-converter.js:30:18)
    at async /usr/app/server/routes.js:19:14
    at async initialize (/usr/app/server/auth/index.js:47:3)
    at async session (/usr/app/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/usr/app/node_modules/koa-bodyparser/index.js:95:5)
    at async /usr/app/server/index.js:43:9
[2021-08-30T10:23:34.357Z] Error: Request unauthorized
    at buildGrpcMetadata (/usr/app/server/temporal-client/with-auth-metadata.js:43:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Proxy.<anonymous> (/usr/app/server/temporal-client/with-auth-metadata.js:20:24)
    at async TemporalClient.getVersionInfo (/usr/app/server/temporal-client/temporal-client.js:294:15)
    at async Proxy.<anonymous> (/usr/app/server/temporal-client/with-error-converter.js:30:18)
    at async /usr/app/server/routes.js:388:15
    at async initialize (/usr/app/server/auth/index.js:47:3)
    at async session (/usr/app/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/usr/app/node_modules/koa-bodyparser/index.js:95:5)
    at async /usr/app/server/index.js:43:9
[2021-08-30T10:23:54.053Z] Error: Request unauthorized
    at buildGrpcMetadata (/usr/app/server/temporal-client/with-auth-metadata.js:43:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Proxy.<anonymous> (/usr/app/server/temporal-client/with-auth-metadata.js:20:24)
    at async TemporalClient.getVersionInfo (/usr/app/server/temporal-client/temporal-client.js:294:15)
    at async Proxy.<anonymous> (/usr/app/server/temporal-client/with-error-converter.js:30:18)
    at async /usr/app/server/routes.js:388:15
    at async initialize (/usr/app/server/auth/index.js:47:3)
    at async session (/usr/app/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/usr/app/node_modules/koa-bodyparser/index.js:95:5)
    at async /usr/app/server/index.js:43:9
```

**Comment by feedmeapples** [comment]
> [2021-08-30T10:14:39.654Z] Error: did not find expected authorization request details in session, req.session["oidc:ids.uat-eureka.uat.eurekacloud.io"] is undefined
    at /usr/app/node_modules/openid-client/lib/passport_strategy.js:128:13
    
Based on the logs ^ found few interesting threads:
https://github.com/panva/node-openid-client/issues/154
https://github.com/panva/node-openid-client/issues/237
https://github.com/okta/okta-oidc-js/issues/271#issuecomment-625398669
https://stackoverflow.com/questions/63259184/node-with-express-session-issue

could you pls check if anything ^ applies to you (ex. multiple web server instances)

**Comment by runzexia** [comment]
thanks for your reply. i missing the log, because it is't always happened, i would check it

**Comment by runzexia** [comment]
found this issue, our ids not support nonce, we plan to support this in our ids
https://github.com/temporalio/web/blob/3060e18033375975da37ca57d01bf42c461375a6/server/auth/index.js#L53
Thanks for your help
