### ISSUE TITLE
run error 

### ISSUE THREAD

**Issue by harshwardhan-bit** [temporalio/web#386]
```
/mytempotest/web/server/index.js:37
    process.env.TEMPORAL_SESSION_SECRET ?? 'ensure secret in production';
                                         ^

SyntaxError: Unexpected token ?
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! temporal-web@1.11.0 dev: `NODE_ENV=development node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the temporal-web@1.11.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-09T11_43_21_484Z-debug.log
```

**Comment by feedmeapples** [comment]
could you provide more details, how do you start the Web?

**Comment by harshwardhan-bit** [comment]
issue resolved 

Thank for you response
