### ISSUE TITLE
Configuring OIDC authentication on the web UI breaks worker polling

### ISSUE THREAD

**Issue by srikanthchelluri** [temporalio/web#409]
We recently enabled OIDC authentication to the web UI using the Helm chart for Temporal. This works as advertised when navigating to the web UI via a browser but we found that it broke worker polling.

I've attached a snippet of the logs from a worker below. They are slightly modified to redact some identifying information:

```
Activity Poller taskQueue="some/Queue", namespace="SOME_NAMESPACE": 5] ERROR io.temporal.internal.worker.Poller - Failure in thread Activity Poller taskQueue="some/Queue", namespace="SOME_NAMESPACE": 5
io.grpc.StatusRuntimeException: NOT_FOUND: namespace ID: 69cf89cf-db87-49eb-9d6a-b6f4f594a093 not found
    at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
    at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
    at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
    at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.pollActivityTaskQueue(WorkflowServiceGrpc.java:2684)
    at io.temporal.internal.worker.ActivityPollTask.poll(ActivityPollTask.java:99)
    at io.temporal.internal.worker.ActivityPollTask.poll(ActivityPollTask.java:39)
    at io.temporal.internal.worker.Poller$PollExecutionTask.run(Poller.java:270)
    at io.temporal.internal.worker.Poller$PollLoopTask.run(Poller.java:235)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

I assume this is not expected behavior - but if it is, please let me know what you think I'm missing. I'm happy to provide any additional details as needed.

**Comment by feedmeapples** [comment]
@srikanthchelluri Web UI is a client and shouldn't really affect the SDKs and worker polling. 

Your error message says "namespace ID: 69cf89cf-db87-49eb-9d6a-b6f4f594a093 not found"
Does tctl output this namespace successfully? ie. `tctl namespace list`

This is unlikely to be a bug and is not a feature request so i'm closing the issue. Though please feel free to open a ticket in our community https://community.temporal.io/ so we can help you out

**Comment by srikanthchelluri** [comment]
Will do, linking the thread here for posterity: https://community.temporal.io/t/not-found-namespace-id-xxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxxxxxxx-not-found/3320
